import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { compareRenderedTree } from "./generated-tree.js";
import {
  AutophoneErrorSchema,
  ClipboardGetRequestSchema,
  ClipboardGetResultSchema,
  ClipboardSetRequestSchema,
  ClipboardSetResultSchema,
  AppActivitiesRequestSchema,
  AppActivitiesResultSchema,
  AppClearDataRequestSchema,
  AppClearDataResultSchema,
  AppInstallRequestSchema,
  AppInstallResultSchema,
  AppInspectRequestSchema,
  AppInspectResultSchema,
  AppListRequestSchema,
  AppListResultSchema,
  AppLinksRequestSchema,
  AppLinksResultSchema,
  AppOpsGetRequestSchema,
  AppOpsGetResultSchema,
  AppCurrentRequestSchema,
  AppCurrentResultSchema,
  AppGraphicsRequestSchema,
  AppGraphicsResultSchema,
  AppLaunchRequestSchema,
  AppLaunchResultSchema,
  AppMemoryRequestSchema,
  AppMemoryResultSchema,
  AppOpenUrlRequestSchema,
  AppOpenUrlResultSchema,
  AppResolveUrlRequestSchema,
  AppResolveUrlResultSchema,
  AppPackageInfoRequestSchema,
  AppPackageInfoResultSchema,
  AppPermissionInspectRequestSchema,
  AppPermissionInspectResultSchema,
  AppPermissionRequestSchema,
  AppPermissionResultSchema,
  AppPidsRequestSchema,
  AppPidsResultSchema,
  AppStopRequestSchema,
  AppStopResultSchema,
  AppStartRequestSchema,
  AppStartResultSchema,
  AppUninstallRequestSchema,
  AppUninstallResultSchema,
  DeviceBatteryGetRequestSchema,
  DeviceBatteryGetResultSchema,
  DeviceTimeGetRequestSchema,
  DeviceTimeGetResultSchema,
  DeviceCurrentUserRequestSchema,
  DeviceCurrentUserResultSchema,
  DeviceAccessibilityGetRequestSchema,
  DeviceAccessibilityGetResultSchema,
  DeviceAnimationsGetRequestSchema,
  DeviceAnimationsGetResultSchema,
  DeviceAnimationsSetRequestSchema,
  DeviceAnimationsSetResultSchema,
  DeviceBrightnessGetRequestSchema,
  DeviceBrightnessGetResultSchema,
  DeviceDetailsRequestSchema,
  DeviceDetailsResultSchema,
  DeviceEnsureReadyRequestSchema,
  DeviceEnsureReadyResultSchema,
  DeviceImeGetRequestSchema,
  DeviceImeGetResultSchema,
  DeviceImeSetRequestSchema,
  DeviceImeSetResultSchema,
  DeviceImeResetRequestSchema,
  DeviceImeResetResultSchema,
  DeviceLocaleGetRequestSchema,
  DeviceLocaleGetResultSchema,
  DeviceListRequestSchema,
  DeviceListResultSchema,
  DeviceNetworkGetRequestSchema,
  DeviceNetworkGetResultSchema,
  DeviceStorageGetRequestSchema,
  DeviceStorageGetResultSchema,
  DeviceNotificationsRequestSchema,
  DeviceNotificationsResultSchema,
  DeviceOrientationRequestSchema,
  DeviceOrientationResultSchema,
  DeviceOrientationSetRequestSchema,
  DeviceOrientationSetResultSchema,
  DeviceRingerGetRequestSchema,
  DeviceRingerGetResultSchema,
  DeviceScreenGetRequestSchema,
  DeviceScreenGetResultSchema,
  DeviceStatusBarRequestSchema,
  DeviceStatusBarResultSchema,
  DeviceStatusBarIconsRequestSchema,
  DeviceStatusBarIconsResultSchema,
  DeviceUsersRequestSchema,
  DeviceUsersResultSchema,
  DeviceVolumeGetRequestSchema,
  DeviceVolumeGetResultSchema,
  DoubleTapRequestSchema,
  DoubleTapResultSchema,
  DragRequestSchema,
  DragResultSchema,
  FindRequestSchema,
  FindResultSchema,
  FileCopyRequestSchema,
  FileCopyResultSchema,
  FileHashRequestSchema,
  FileHashResultSchema,
  FileListRequestSchema,
  FileListResultSchema,
  FileMkdirRequestSchema,
  FileMkdirResultSchema,
  FileMoveRequestSchema,
  FileMoveResultSchema,
  FilePullRequestSchema,
  FilePullResultSchema,
  FilePushRequestSchema,
  FilePushResultSchema,
  FileRmRequestSchema,
  FileRmResultSchema,
  FileStatRequestSchema,
  FileStatResultSchema,
  KeyPressRequestSchema,
  KeyPressResultSchema,
  LongPressRequestSchema,
  LongPressResultSchema,
  LogsDumpRequestSchema,
  LogsDumpResultSchema,
  ObserveResultSchema,
  ProofManifestSchema,
  ProofRefSchema,
  RecipeFileSchema,
  RecipeRunRequestSchema,
  RecipeRunResultSchema,
  ResponseEnvelopeSchema,
  ScreenshotRequestSchema,
  ScreenshotResultSchema,
  ScreenrecordRequestSchema,
  ScreenrecordResultSchema,
  ScrollRequestSchema,
  ScrollResultSchema,
  ScrollUntilRequestSchema,
  ScrollUntilResultSchema,
  SelectorSchema,
  SnapshotSchema,
  TapRequestSchema,
  TapResultSchema,
  TextClearRequestSchema,
  TextClearResultSchema,
  TextInputRequestSchema,
  TextInputResultSchema,
  UiNodeSchema,
  WaitAppRequestSchema,
  WaitAppResultSchema,
  WaitUiRequestSchema,
  WaitUiResultSchema
} from "../src/contracts/index.js";

const root = dirname(dirname(fileURLToPath(import.meta.url)));

const schemas = {
  "error.schema.json": AutophoneErrorSchema,
  "proof-ref.schema.json": ProofRefSchema,
  "proof-manifest.schema.json": ProofManifestSchema,
  "ui-node.schema.json": UiNodeSchema,
  "snapshot.schema.json": SnapshotSchema,
  "selector.schema.json": SelectorSchema,
  "device-info-request.schema.json": DeviceDetailsRequestSchema,
  "device-info-result.schema.json": DeviceDetailsResultSchema,
  "device-info-response.schema.json": ResponseEnvelopeSchema(DeviceDetailsResultSchema),
  "device-ensure-ready-request.schema.json": DeviceEnsureReadyRequestSchema,
  "device-ensure-ready-result.schema.json": DeviceEnsureReadyResultSchema,
  "device-ensure-ready-response.schema.json": ResponseEnvelopeSchema(DeviceEnsureReadyResultSchema),
  "device-list-request.schema.json": DeviceListRequestSchema,
  "device-list-result.schema.json": DeviceListResultSchema,
  "device-list-response.schema.json": ResponseEnvelopeSchema(DeviceListResultSchema),
  "device-brightness-get-request.schema.json": DeviceBrightnessGetRequestSchema,
  "device-brightness-get-result.schema.json": DeviceBrightnessGetResultSchema,
  "device-brightness-get-response.schema.json": ResponseEnvelopeSchema(DeviceBrightnessGetResultSchema),
  "device-animations-get-request.schema.json": DeviceAnimationsGetRequestSchema,
  "device-animations-get-result.schema.json": DeviceAnimationsGetResultSchema,
  "device-animations-get-response.schema.json": ResponseEnvelopeSchema(DeviceAnimationsGetResultSchema),
  "device-animations-set-request.schema.json": DeviceAnimationsSetRequestSchema,
  "device-animations-set-result.schema.json": DeviceAnimationsSetResultSchema,
  "device-animations-set-response.schema.json": ResponseEnvelopeSchema(DeviceAnimationsSetResultSchema),
  "device-accessibility-get-request.schema.json": DeviceAccessibilityGetRequestSchema,
  "device-accessibility-get-result.schema.json": DeviceAccessibilityGetResultSchema,
  "device-accessibility-get-response.schema.json": ResponseEnvelopeSchema(DeviceAccessibilityGetResultSchema),
  "device-ime-get-request.schema.json": DeviceImeGetRequestSchema,
  "device-ime-get-result.schema.json": DeviceImeGetResultSchema,
  "device-ime-get-response.schema.json": ResponseEnvelopeSchema(DeviceImeGetResultSchema),
  "device-ime-set-request.schema.json": DeviceImeSetRequestSchema,
  "device-ime-set-result.schema.json": DeviceImeSetResultSchema,
  "device-ime-set-response.schema.json": ResponseEnvelopeSchema(DeviceImeSetResultSchema),
  "device-ime-reset-request.schema.json": DeviceImeResetRequestSchema,
  "device-ime-reset-result.schema.json": DeviceImeResetResultSchema,
  "device-ime-reset-response.schema.json": ResponseEnvelopeSchema(DeviceImeResetResultSchema),
  "device-network-get-request.schema.json": DeviceNetworkGetRequestSchema,
  "device-network-get-result.schema.json": DeviceNetworkGetResultSchema,
  "device-network-get-response.schema.json": ResponseEnvelopeSchema(DeviceNetworkGetResultSchema),
  "device-storage-get-request.schema.json": DeviceStorageGetRequestSchema,
  "device-storage-get-result.schema.json": DeviceStorageGetResultSchema,
  "device-storage-get-response.schema.json": ResponseEnvelopeSchema(DeviceStorageGetResultSchema),
  "device-battery-get-request.schema.json": DeviceBatteryGetRequestSchema,
  "device-battery-get-result.schema.json": DeviceBatteryGetResultSchema,
  "device-battery-get-response.schema.json": ResponseEnvelopeSchema(DeviceBatteryGetResultSchema),
  "device-time-get-request.schema.json": DeviceTimeGetRequestSchema,
  "device-time-get-result.schema.json": DeviceTimeGetResultSchema,
  "device-time-get-response.schema.json": ResponseEnvelopeSchema(DeviceTimeGetResultSchema),
  "device-locale-get-request.schema.json": DeviceLocaleGetRequestSchema,
  "device-locale-get-result.schema.json": DeviceLocaleGetResultSchema,
  "device-locale-get-response.schema.json": ResponseEnvelopeSchema(DeviceLocaleGetResultSchema),
  "device-orientation-request.schema.json": DeviceOrientationRequestSchema,
  "device-orientation-result.schema.json": DeviceOrientationResultSchema,
  "device-orientation-response.schema.json": ResponseEnvelopeSchema(DeviceOrientationResultSchema),
  "device-orientation-set-request.schema.json": DeviceOrientationSetRequestSchema,
  "device-orientation-set-result.schema.json": DeviceOrientationSetResultSchema,
  "device-orientation-set-response.schema.json": ResponseEnvelopeSchema(DeviceOrientationSetResultSchema),
  "device-statusbar-request.schema.json": DeviceStatusBarRequestSchema,
  "device-statusbar-result.schema.json": DeviceStatusBarResultSchema,
  "device-statusbar-response.schema.json": ResponseEnvelopeSchema(DeviceStatusBarResultSchema),
  "device-statusbar-icons-request.schema.json": DeviceStatusBarIconsRequestSchema,
  "device-statusbar-icons-result.schema.json": DeviceStatusBarIconsResultSchema,
  "device-statusbar-icons-response.schema.json": ResponseEnvelopeSchema(DeviceStatusBarIconsResultSchema),
  "device-volume-get-request.schema.json": DeviceVolumeGetRequestSchema,
  "device-volume-get-result.schema.json": DeviceVolumeGetResultSchema,
  "device-volume-get-response.schema.json": ResponseEnvelopeSchema(DeviceVolumeGetResultSchema),
  "device-ringer-get-request.schema.json": DeviceRingerGetRequestSchema,
  "device-ringer-get-result.schema.json": DeviceRingerGetResultSchema,
  "device-ringer-get-response.schema.json": ResponseEnvelopeSchema(DeviceRingerGetResultSchema),
  "device-notifications-get-request.schema.json": DeviceNotificationsRequestSchema,
  "device-notifications-get-result.schema.json": DeviceNotificationsResultSchema,
  "device-notifications-get-response.schema.json": ResponseEnvelopeSchema(DeviceNotificationsResultSchema),
  "device-screen-get-request.schema.json": DeviceScreenGetRequestSchema,
  "device-screen-get-result.schema.json": DeviceScreenGetResultSchema,
  "device-screen-get-response.schema.json": ResponseEnvelopeSchema(DeviceScreenGetResultSchema),
  "device-current-user-request.schema.json": DeviceCurrentUserRequestSchema,
  "device-current-user-result.schema.json": DeviceCurrentUserResultSchema,
  "device-current-user-response.schema.json": ResponseEnvelopeSchema(DeviceCurrentUserResultSchema),
  "device-users-request.schema.json": DeviceUsersRequestSchema,
  "device-users-result.schema.json": DeviceUsersResultSchema,
  "device-users-response.schema.json": ResponseEnvelopeSchema(DeviceUsersResultSchema),
  "app-list-request.schema.json": AppListRequestSchema,
  "app-list-result.schema.json": AppListResultSchema,
  "app-list-response.schema.json": ResponseEnvelopeSchema(AppListResultSchema),
  "app-activities-request.schema.json": AppActivitiesRequestSchema,
  "app-activities-result.schema.json": AppActivitiesResultSchema,
  "app-activities-response.schema.json": ResponseEnvelopeSchema(AppActivitiesResultSchema),
  "app-clear-data-request.schema.json": AppClearDataRequestSchema,
  "app-clear-data-result.schema.json": AppClearDataResultSchema,
  "app-clear-data-response.schema.json": ResponseEnvelopeSchema(AppClearDataResultSchema),
  "app-install-request.schema.json": AppInstallRequestSchema,
  "app-install-result.schema.json": AppInstallResultSchema,
  "app-install-response.schema.json": ResponseEnvelopeSchema(AppInstallResultSchema),
  "app-inspect-request.schema.json": AppInspectRequestSchema,
  "app-inspect-result.schema.json": AppInspectResultSchema,
  "app-inspect-response.schema.json": ResponseEnvelopeSchema(AppInspectResultSchema),
  "app-package-info-request.schema.json": AppPackageInfoRequestSchema,
  "app-package-info-result.schema.json": AppPackageInfoResultSchema,
  "app-package-info-response.schema.json": ResponseEnvelopeSchema(AppPackageInfoResultSchema),
  "app-links-request.schema.json": AppLinksRequestSchema,
  "app-links-result.schema.json": AppLinksResultSchema,
  "app-links-response.schema.json": ResponseEnvelopeSchema(AppLinksResultSchema),
  "app-ops-get-request.schema.json": AppOpsGetRequestSchema,
  "app-ops-get-result.schema.json": AppOpsGetResultSchema,
  "app-ops-get-response.schema.json": ResponseEnvelopeSchema(AppOpsGetResultSchema),
  "app-pids-request.schema.json": AppPidsRequestSchema,
  "app-pids-result.schema.json": AppPidsResultSchema,
  "app-pids-response.schema.json": ResponseEnvelopeSchema(AppPidsResultSchema),
  "app-memory-request.schema.json": AppMemoryRequestSchema,
  "app-memory-result.schema.json": AppMemoryResultSchema,
  "app-memory-response.schema.json": ResponseEnvelopeSchema(AppMemoryResultSchema),
  "app-graphics-request.schema.json": AppGraphicsRequestSchema,
  "app-graphics-result.schema.json": AppGraphicsResultSchema,
  "app-graphics-response.schema.json": ResponseEnvelopeSchema(AppGraphicsResultSchema),
  "app-current-request.schema.json": AppCurrentRequestSchema,
  "app-current-result.schema.json": AppCurrentResultSchema,
  "app-current-response.schema.json": ResponseEnvelopeSchema(AppCurrentResultSchema),
  "app-launch-request.schema.json": AppLaunchRequestSchema,
  "app-launch-result.schema.json": AppLaunchResultSchema,
  "app-launch-response.schema.json": ResponseEnvelopeSchema(AppLaunchResultSchema),
  "app-open-url-request.schema.json": AppOpenUrlRequestSchema,
  "app-open-url-result.schema.json": AppOpenUrlResultSchema,
  "app-open-url-response.schema.json": ResponseEnvelopeSchema(AppOpenUrlResultSchema),
  "app-resolve-url-request.schema.json": AppResolveUrlRequestSchema,
  "app-resolve-url-result.schema.json": AppResolveUrlResultSchema,
  "app-resolve-url-response.schema.json": ResponseEnvelopeSchema(AppResolveUrlResultSchema),
  "app-permission-request.schema.json": AppPermissionRequestSchema,
  "app-permission-result.schema.json": AppPermissionResultSchema,
  "app-permission-response.schema.json": ResponseEnvelopeSchema(AppPermissionResultSchema),
  "app-permission-inspect-request.schema.json": AppPermissionInspectRequestSchema,
  "app-permission-inspect-result.schema.json": AppPermissionInspectResultSchema,
  "app-permission-inspect-response.schema.json": ResponseEnvelopeSchema(AppPermissionInspectResultSchema),
  "app-stop-request.schema.json": AppStopRequestSchema,
  "app-stop-result.schema.json": AppStopResultSchema,
  "app-stop-response.schema.json": ResponseEnvelopeSchema(AppStopResultSchema),
  "app-uninstall-request.schema.json": AppUninstallRequestSchema,
  "app-uninstall-result.schema.json": AppUninstallResultSchema,
  "app-uninstall-response.schema.json": ResponseEnvelopeSchema(AppUninstallResultSchema),
  "app-start-request.schema.json": AppStartRequestSchema,
  "app-start-result.schema.json": AppStartResultSchema,
  "app-start-response.schema.json": ResponseEnvelopeSchema(AppStartResultSchema),
  "find-request.schema.json": FindRequestSchema,
  "find-result.schema.json": FindResultSchema,
  "find-response.schema.json": ResponseEnvelopeSchema(FindResultSchema),
  "files-push-request.schema.json": FilePushRequestSchema,
  "files-push-result.schema.json": FilePushResultSchema,
  "files-push-response.schema.json": ResponseEnvelopeSchema(FilePushResultSchema),
  "files-pull-request.schema.json": FilePullRequestSchema,
  "files-pull-result.schema.json": FilePullResultSchema,
  "files-pull-response.schema.json": ResponseEnvelopeSchema(FilePullResultSchema),
  "files-hash-request.schema.json": FileHashRequestSchema,
  "files-hash-result.schema.json": FileHashResultSchema,
  "files-hash-response.schema.json": ResponseEnvelopeSchema(FileHashResultSchema),
  "files-list-request.schema.json": FileListRequestSchema,
  "files-list-result.schema.json": FileListResultSchema,
  "files-list-response.schema.json": ResponseEnvelopeSchema(FileListResultSchema),
  "files-mkdir-request.schema.json": FileMkdirRequestSchema,
  "files-mkdir-result.schema.json": FileMkdirResultSchema,
  "files-mkdir-response.schema.json": ResponseEnvelopeSchema(FileMkdirResultSchema),
  "files-copy-request.schema.json": FileCopyRequestSchema,
  "files-copy-result.schema.json": FileCopyResultSchema,
  "files-copy-response.schema.json": ResponseEnvelopeSchema(FileCopyResultSchema),
  "files-move-request.schema.json": FileMoveRequestSchema,
  "files-move-result.schema.json": FileMoveResultSchema,
  "files-move-response.schema.json": ResponseEnvelopeSchema(FileMoveResultSchema),
  "files-stat-request.schema.json": FileStatRequestSchema,
  "files-stat-result.schema.json": FileStatResultSchema,
  "files-stat-response.schema.json": ResponseEnvelopeSchema(FileStatResultSchema),
  "files-rm-request.schema.json": FileRmRequestSchema,
  "files-rm-result.schema.json": FileRmResultSchema,
  "files-rm-response.schema.json": ResponseEnvelopeSchema(FileRmResultSchema),
  "key-press-request.schema.json": KeyPressRequestSchema,
  "key-press-result.schema.json": KeyPressResultSchema,
  "key-press-response.schema.json": ResponseEnvelopeSchema(KeyPressResultSchema),
  "clipboard-get-request.schema.json": ClipboardGetRequestSchema,
  "clipboard-get-result.schema.json": ClipboardGetResultSchema,
  "clipboard-get-response.schema.json": ResponseEnvelopeSchema(ClipboardGetResultSchema),
  "clipboard-set-request.schema.json": ClipboardSetRequestSchema,
  "clipboard-set-result.schema.json": ClipboardSetResultSchema,
  "clipboard-set-response.schema.json": ResponseEnvelopeSchema(ClipboardSetResultSchema),
  "long-press-request.schema.json": LongPressRequestSchema,
  "long-press-result.schema.json": LongPressResultSchema,
  "long-press-response.schema.json": ResponseEnvelopeSchema(LongPressResultSchema),
  "logs-dump-request.schema.json": LogsDumpRequestSchema,
  "logs-dump-result.schema.json": LogsDumpResultSchema,
  "logs-dump-response.schema.json": ResponseEnvelopeSchema(LogsDumpResultSchema),
  "screenshot-request.schema.json": ScreenshotRequestSchema,
  "screenshot-result.schema.json": ScreenshotResultSchema,
  "screenshot-response.schema.json": ResponseEnvelopeSchema(ScreenshotResultSchema),
  "screenrecord-request.schema.json": ScreenrecordRequestSchema,
  "screenrecord-result.schema.json": ScreenrecordResultSchema,
  "screenrecord-response.schema.json": ResponseEnvelopeSchema(ScreenrecordResultSchema),
  "scroll-request.schema.json": ScrollRequestSchema,
  "scroll-result.schema.json": ScrollResultSchema,
  "scroll-response.schema.json": ResponseEnvelopeSchema(ScrollResultSchema),
  "scroll-until-request.schema.json": ScrollUntilRequestSchema,
  "scroll-until-result.schema.json": ScrollUntilResultSchema,
  "scroll-until-response.schema.json": ResponseEnvelopeSchema(ScrollUntilResultSchema),
  "drag-request.schema.json": DragRequestSchema,
  "drag-result.schema.json": DragResultSchema,
  "drag-response.schema.json": ResponseEnvelopeSchema(DragResultSchema),
  "tap-request.schema.json": TapRequestSchema,
  "tap-result.schema.json": TapResultSchema,
  "tap-response.schema.json": ResponseEnvelopeSchema(TapResultSchema),
  "double-tap-request.schema.json": DoubleTapRequestSchema,
  "double-tap-result.schema.json": DoubleTapResultSchema,
  "double-tap-response.schema.json": ResponseEnvelopeSchema(DoubleTapResultSchema),
  "text-clear-request.schema.json": TextClearRequestSchema,
  "text-clear-result.schema.json": TextClearResultSchema,
  "text-clear-response.schema.json": ResponseEnvelopeSchema(TextClearResultSchema),
  "text-input-request.schema.json": TextInputRequestSchema,
  "text-input-result.schema.json": TextInputResultSchema,
  "text-input-response.schema.json": ResponseEnvelopeSchema(TextInputResultSchema),
  "wait-ui-request.schema.json": WaitUiRequestSchema,
  "wait-ui-result.schema.json": WaitUiResultSchema,
  "wait-ui-response.schema.json": ResponseEnvelopeSchema(WaitUiResultSchema),
  "wait-app-request.schema.json": WaitAppRequestSchema,
  "wait-app-result.schema.json": WaitAppResultSchema,
  "wait-app-response.schema.json": ResponseEnvelopeSchema(WaitAppResultSchema),
  "recipe-file.schema.json": RecipeFileSchema,
  "recipe-run-request.schema.json": RecipeRunRequestSchema,
  "recipe-run-result.schema.json": RecipeRunResultSchema,
  "recipe-run-response.schema.json": ResponseEnvelopeSchema(RecipeRunResultSchema),
  "observe-response.schema.json": ResponseEnvelopeSchema(ObserveResultSchema),
} satisfies Record<string, z.ZodTypeAny>;

const outputDir = join(root, "schemas");

const rendered = new Map<string, string>();
for (const [fileName, schema] of Object.entries(schemas)) {
  const jsonSchema = z.toJSONSchema(schema);
  Object.assign(jsonSchema, { $id: fileName.replace(".schema.json", "") });
  rendered.set(fileName, `${JSON.stringify(jsonSchema, null, 2)}\n`);
}

if (process.argv.includes("--check")) {
  const drift = compareRenderedTree(outputDir, rendered);
  if (drift.length > 0) {
    process.stderr.write("Generated schemas are out of sync with src/contracts.\n");
    process.stderr.write("Run pnpm schemas and commit the resulting schemas/ changes.\n");
    for (const line of drift) {
      process.stderr.write(`  ${line}\n`);
    }
    process.exit(1);
  }
  process.stdout.write(`schemas: ${rendered.size} files match src/contracts\n`);
} else {
  await rm(outputDir, { recursive: true, force: true });
  await mkdir(outputDir, { recursive: true });
  for (const [fileName, contents] of rendered) {
    await writeFile(join(outputDir, fileName), contents);
  }
}
